In [1]:
import theano


In [2]:
import sys 


In [3]:
print(sys.path)

['', '/usr/local/src/jupyterhub', '/anaconda3/lib/python35.zip', '/anaconda3/lib/python3.5', '/anaconda3/lib/python3.5/plat-linux', '/anaconda3/lib/python3.5/lib-dynload', '/anaconda3/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg', '/anaconda3/lib/python3.5/site-packages/setuptools-20.7.0-py3.5.egg', '/anaconda3/lib/python3.5/site-packages', '/anaconda3/lib/python3.5/site-packages/IPython/extensions', '/global/u1/s/ssingh79/.ipython']


In [ ]:
import theano
import numpy
import theano.tensor as T
from theano import function
rng = numpy.random

x = T.dscalar('x')
y = T.dscalar('y')
z = x + y 
f = function([x, y],z)
#f(2,3)

m = T.matrix('m')
n = T.matrix('n')
b = T.dscalar('b')
mult = m * n + b
fmat = function([m, n, b],mult)
#fmat([[1, 2, 3 ,4 ],[3, 5, 7, 8]], [[1, 2, 3 ,4 ],[3, 5, 7, 8]],1.0)
#fmat() 

a = T.vector()
out = a + a**2
fpow = function([a],out)
#fpow(numpy.array([1, 2, 3, 4, 5]))

#logistic
x_num = T.matrix('x_num')
s = 1/(1 + T.exp(-x_num))
flogr = function([x_num], s)
#flogr([[1, -1.293537], [-1.637429302, 0.02362784]])

#random var
D = rng.randn(5,5)
print(D)


In [8]:
import numpy as np 
img = np.zeros((5,5), dtype=np.int)
a =0; 
for i in range(0,5):
    for j in range(0,5):
        img[i][j] = a+1
        a= a+1
        
print(img)
        

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [2]:
import sys
print(sys.path)

['', '/usr/local/src/jupyterhub', '/anaconda3/lib/python35.zip', '/anaconda3/lib/python3.5', '/anaconda3/lib/python3.5/plat-linux', '/anaconda3/lib/python3.5/lib-dynload', '/anaconda3/lib/python3.5/site-packages/Sphinx-1.4.1-py3.5.egg', '/anaconda3/lib/python3.5/site-packages/setuptools-20.7.0-py3.5.egg', '/anaconda3/lib/python3.5/site-packages', '/anaconda3/lib/python3.5/site-packages/IPython/extensions', '/global/u1/s/ssingh79/.ipython']


In [ ]:
!top

top - 16:04:39 up 62 days, 16:54,  0 users,  load average: 1.30, 0.87, 0.47
Tasks: 571 total,   2 running, 565 sleeping,   1 stopped,   3 zombie
Cpu(s):  7.0%us,  0.3%sy,  0.0%ni, 92.6%id,  0.1%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  132134508k total, 83554932k used, 48579576k free,   665232k buffers
Swap:  4194296k total,  4194256k used,       40k free, 13792364k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND            
41732 ssingh79  20   0 4065m 983m  18m R 78.0  0.8   4:49.55 python             
   54 nslcd     20   0  446m 3884 1780 S  6.0  0.0   1:03.27 nslcd              
43637 regan     20   0 1797m 131m 1368 S  4.5  0.1 425:41.96 python             
37825 racah     20   0  696m  96m 2084 S  3.0  0.1  33:09.03 python             
41916 ssingh79  20   0 17512 1608  912 R  3.0  0.0   0:00.05 top                
 6360 jpwilson  20   0  328m  32m 1032 S  1.5  0.0  45:00.91 jupyterhub-sing    
41903 ssingh79  20   0  620m  34m 6688 S  1.5  0.0   0:00.84 p